platform :ios, '7.0'

pod 'MagicalRecord' , '~> 2.2'
pod 'AFNetworking' , '~> 2.3.1'
pod 'MBProgressHUD' , '~> 0.8'
pod 'iCarousel' , '~> 1.6.3'
pod 'RESideMenu' , '~> 4.0.5'
pod 'NewRelicAgent' , '~> 3.343'